# Generated by Django 3.2 on 2023-07-27 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=355, verbose_name='Название блюда')),
                ('description', models.CharField(max_length=355, verbose_name='Описание блюда')),
                ('compound', models.CharField(max_length=500, verbose_name='Состав блюда')),
                ('weight', models.IntegerField(verbose_name='Вес блюда')),
                ('calories', models.IntegerField(verbose_name='Калорийность')),
                ('price', models.IntegerField(verbose_name='Цена блюда')),
                ('count', models.IntegerField(default=1, verbose_name='Количество блюда')),
                ('type', models.CharField(blank=True, choices=[('hot_dishes', 'Горячие блюда'), ('soups', 'Супы'), ('paste', 'Паста'), ('snacks', 'Закуски'), ('salads', 'Салаты'), ('side_dishes', 'Гарниры'), ('pizza', 'Пицца'), ('burgers', 'Бургеры'), ('dessert', 'Десерты'), ('drinks', 'Напитки'), ('khachapuri', 'Хачапури'), ('ossetian_pies', 'Осетинские пироги'), ('sauces', 'Соусы'), ('dishes_grill', 'Блюда на мангале'), ('rolls', 'Роллы'), ('beer_snacks', 'Пивные закуски'), ('bread', 'Хлеб'), ('wok', 'Вок')], max_length=50, null=True, verbose_name='Тип блюда')),
                ('promotion', models.CharField(blank=True, choices=[('promotion', 'Акция'), ('recommend', 'Рекомендуем')], max_length=50, null=True, verbose_name='Акция блюда')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='backend_media/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='Количество блюд')),
                ('price', models.IntegerField(verbose_name='Цена блюда')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart_goods', to='goods.goods', verbose_name='Покупка')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
            },
        ),
    ]
