# Generated by Django 3.2 on 2023-09-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Улица доставки'),
        ),
    ]
